app = "interex-staging"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
swap_size_mb = 512

[experimental]
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[build]
dockerfile = "/other/Dockerfile"
ignorefile = "/other/Dockerfile.dockerignore"

# Modern HTTP service (replaces [[services]])
[http_service]
internal_port = 8080
processes = ["app"]
force_https = true
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "requests"
soft_limit = 80
hard_limit = 100

# Health checks (matches /resources/healthcheck route in your Express app)
[[http_service.checks]]
grace_period = "30s"
interval     = "15s"
timeout      = "10s"
method       = "GET"
path         = "/resources/healthcheck"

[[http_service.checks]]
   grace_period = "30s"
   interval     = "30s"
   timeout      = "10s"
   method       = "GET"
   path         = "/litefs/health"
